### ISSUE TITLE
Post#create error: undefined method `users' for #<Hurley::Client:0x00000001be1990>

### ISSUE THREAD

**Issue by ben-biddington** [kkirsche/medium-sdk-ruby#2]
Note: this is for revision 9f97af7928563d732d6552e9c1b7f286c5b1ffb1 which matches [version `1.0.1` of the published gem](https://rubygems.org/gems/medium-sdk-ruby/versions/1.0.1). The public interface has changed since, but that change has not been released (master is out of sync with gem).

Failing test [here](https://github.com/ben-biddington/medium-sdk-ruby/blob/f/ailing_posts/test/spec/posts_spec.rb#L16).

Hey I have been trying to create some posts with the SDK and I am getting errors like:

```
 2) Error:
Medium Posts Client::The Medium SDK Gem Posts Resource Client#test_0002_can be asked to create a draft:
NoMethodError: undefined method `users' for #<Hurley::Client:0x00000001be1990>
    /home/ben/sauce/medium-sdk-ruby/lib/medium/posts.rb:34:in `create'
    /home/ben/sauce/medium-sdk-ruby/test/spec/posts_spec.rb:17:in `block (2 levels) in <module:MediumSpec>'
```

To get it to work I had to do something like:

```
def create(opts)
  require 'json'

  me = JSON.parse(@client.get('me').body)

  opts = opts.merge( author_id: me['data']['id'] )

  @client.post "users/#{me['data']['id']}/posts", build_request_with(opts)
end
```

**Comment by kkirsche** [comment]
I believe this was fixed by https://github.com/kkirsche/medium-sdk-ruby/pull/1

I've just pushed the version out to RubyGems (my bad on the delay) so give it a shot and let me know if it's fixed for you

**Comment by kftwotwo** [comment]
I do not understand the documentation @kkirsche could you give a example of getting posts

**Comment by kkirsche** [comment]
Please do not hijack unrelated issues @kfwotwo, instead create a new own for your issue.
