### ISSUE TITLE
Updated readme?

### ISSUE THREAD

**Issue by marckohlbrugge** [kkirsche/medium-sdk-ruby#4]
Could you please update the readme file with instructions on how to get set up?

For example it seems like the gem is renamed to `medium-sdk-ruby` and `require 'medium-sdk-ruby'` doesn't work.

**Comment by schlomok** [comment]
Also experiencing an error when calling `require 'medium-sdk-ruby'`

**Comment by kkirsche** [comment]
Please post the exact error message you are receiving.

**Comment by kkirsche** [comment]
Do `require 'medium'`
